using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SmartHome
{
    partial class SimulatorGUI
    {
        // Class to hold the time
        protected Time time;

        protected void initSimulatorGUI() {
            time = new Time(0.0);
        } // initSimulatorGUI
        
        /// <summary>
        ///     Action handler for the Submmit Button related to time management
        /// </summary>
        /// <param name="sender">Autogenerated</param>
        /// <param name="e">Autogenerated</param>
        private void buttonSubmit_Click(object sender, EventArgs e)
        {
            Console.WriteLine(comboBoxHours.SelectedItem.ToString());
            comboBoxMinutes.SelectedItem.ToString();
            String time = comboBoxHours.SelectedItem.ToString() + "," + comboBoxMinutes.SelectedItem.ToString();
            this.time.setTime(Convert.ToDouble(time));
            refreshTime();
        }//buttonSubmit_Click
    }
}
