//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace Unican.smartHome
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public sealed partial class SmartHome
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateSmartHomeMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Floors.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Unican.smartHome.smartHomeDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"SmartHome", "", "Floors"),
						"DSL0001", this);
			}
		} // ValidateSmartHomeMultiplicity
	} // class SmartHome
} // Unican.smartHome

namespace Unican.smartHome
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Floor
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateFloorMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Rooms.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Unican.smartHome.smartHomeDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Floor", this.Name, "Rooms"),
						"DSL0001", this);
			}
		} // ValidateFloorMultiplicity
	} // class Floor
} // Unican.smartHome

	
 