//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unican.smartHome
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "sh";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"smartHome";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Unican";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID smartHomeDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(smartHomeCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID smartHomeExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(smartHomeCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewsmartHomeExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(smartHomeCommandSetId), 0x0001);
	
		// Package identifier
		public const string smartHomePackageId = "e7461eba-3365-432f-be54-917d1b993741";
		
		// Editor factory identifier
		public const string smartHomeEditorFactoryId = "52610b45-775b-4251-bb65-fa99963408c9";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string smartHomeModelExplorerToolWindowId = "46470cba-a2b8-49df-9ba1-8058e55a71b7";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Unican.smartHome
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string smartHomeCommandSetId = "39b5a467-d11e-4c8d-b10a-f7cf31941954";
	}
}