using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace SmartHome
{
    public partial class GatewayGUI
    {
        //Constants
        private const int TVWATCHING = 35;
        private const int READING = 100;
        private const int NORMAL = 70;
        private const int AMBIENT = 50;

       
        /// <summary>
        /// Event handler to control scroll trackbar event
        /// </summary>
        /// <param name="sender">Autogenerated</param>
        /// <param name="e">Autogenerated</param>        
        private void trackbar_Scroll_ligthing(object sender, EventArgs e)
        {
            gateway.lightMng_allAdjustLights(trackBar_ligthing.Value);
            combo_predefinedValues.SelectedIndex = 0;
        }// trackbar_Scroll_ligthing

        /// <summary>
        /// Event handler to control enter key event
        /// </summary>
        /// <param name="sender">Autogenerated</param>
        /// <param name="e">Autogenerated</param>
        private void textLigthing_KeyDown(Object sender, KeyEventArgs e)
        {
            if (e.KeyValue == 13)
            { //Enter Key
                try
                {
                    int lighting = Convert.ToInt32(text_ligthing.Text);
                    gateway.lightMng_allAdjustLights(lighting);
                    combo_predefinedValues.SelectedIndex = 0;
                }
                catch (Exception exception)
                {
                    MessageBox.Show("Insert a correct ligthing value(integer between 0 and 100)", "Input error", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                }// catch
            }//if            
        }//textligthing_KeyDown


        /// <summary>
        /// Event handler to control predefined values
        /// </summary>
        /// <param name="sender">Autogenerated</param>
        /// <param name="e">Autogenerated</param>
        private void combo_predefinedValues_SelectedIndexChanged(object sender, EventArgs e)
        {
            switch (combo_predefinedValues.SelectedIndex)
            {
                case 1:
                    gateway.lightMng_allAdjustLights(TVWATCHING);
                    break;
                case 2:
                    gateway.lightMng_allAdjustLights(READING);
                    break;
                case 3:
                    gateway.lightMng_allAdjustLights(NORMAL);
                    break;
                case 4:
                    gateway.lightMng_allAdjustLights(AMBIENT);
                    break;
            }//switch

        }// combo_predefinedValues_SelectedIndexChanged

        /// <summary>
        /// Event handler to control enter key event for a specific room
        /// </summary>
        /// <param name="sender">Autogenerated</param>
        /// <param name="e">Autogenerated</param>
        private void textLigthingByRoom_KeyDown(Object sender, KeyEventArgs e)
        {
            int id_ligth = inverseDictionaryTextLigthing[(TextBox)sender];
            if (e.KeyValue == 13) //Enter Key
            {
                try
                {
                    int ligthing = Convert.ToInt32(dictionaryTextLigthingByRoom[id_ligth].Text);
                    gateway.lightMng_adjustLight(id_ligth, ligthing);
                    dictionaryComboBoxPredefinedValues[id_ligth].SelectedIndex = 0;
                }// try
                catch (Exception exception)
                {
                    MessageBox.Show("Insert a correct ligthing value(integer between 0 and 100)", "Input error", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                }// catch
            }//if            
        }//textLigthingByRoom_KeyDown

        /// <summary>
        /// Event handler to control scroll trackbar event for a specific room
        /// </summary>
        /// <param name="sender">Autogenerated</param>
        /// <param name="e">Autogenerated</param>
        private void trackbarLigthingByRoom_Scroll(object sender, EventArgs e)
        {
            int id_ligth = inverseDictionaryTrackBarLigthing[(TrackBar)sender];
            gateway.lightMng_adjustLight(id_ligth, dictionaryTrackBarLigthingByRoom[id_ligth].Value);
            dictionaryComboBoxPredefinedValues[id_ligth].SelectedIndex = 0;
        }// trackbarLigthingByRoom_Scroll

        /// <summary>
        /// Event handler to control predefined values for a specific room
        /// </summary>
        /// <param name="sender">Autogenerated</param>
        /// <param name="e">Autogenerated</param>
        private void combo_predefinedValues_SelectedIndexChangedByRoom(object sender, EventArgs e)
        {
            int id_ligth = inverseDictComboBoxPredefinedValues[(ComboBox)sender];
            switch (dictionaryComboBoxPredefinedValues[id_ligth].SelectedIndex)
            {
                case 1:
                    gateway.lightMng_adjustLight(id_ligth, TVWATCHING);
                    break;
                case 2:
                    gateway.lightMng_adjustLight(id_ligth, READING);
                    break;
                case 3:
                    gateway.lightMng_adjustLight(id_ligth, NORMAL);
                    break;
                case 4:
                    gateway.lightMng_adjustLight(id_ligth, AMBIENT);
                    break;
            }//switch
        }//combo_predefinedValues_SelectedIndexChangedByRoom
    }// GatewayGUI
}// SmartHome
